### ISSUE TITLE
[native_pdf_view] Add Zooming  without pixel loss

### ISSUE THREAD

**Issue by ShashankSirmour** [rbcprolabs/packages.flutter#6]
**Package name**
A name of package whom this idea concerns. Ex. `native_color`
zoomable image view
**Is your feature request related to a problem? Please describe.**
I want to zoom in the rendered I tried zoomable image package but as its just image with low pixel I lose pixels   
**Describe the solution you'd like**
I want to render a high-quality image so no issue for pixel loss or update pixel by taking an image from the zoomable image I mean just  Zoomable pdf renderer
**Describe alternatives you've considered**

**Additional context**

**Comment by SergeShkurko** [comment]
in version 1.5.0 added crop attributes in render options

**Comment by deakjahn** [comment]
Yes, the crop is there but the view makes no attempt at reloading the contents when the zoom changes. :-)

**Comment by deakjahn** [comment]
I found a possible solution, if you would like to check it out. Instead of `ExtendedImage`, you might want to switch to [`FlutterMap`.](https://pub.dev/packages/flutter_map). Yep, I know, it seems strange at first. But, although it's conceived for maps, it could be used all right. It has full support for tiling smaller parts to show a larger picture, with pinch zoom and everything. And a `FileTileProvider` that you could extend to return the actual tiles of the PDF. When at zoom level 1, nothing would change but at higher zoom levels, you could generate (and cache) the smaller tiles using the crop approach.

I tried to experiment with it a little but I don't know if I can dedicate enough time to it right now. So I thought I'd mention it up front if you think you're interested to look into it. :-)

**Comment by SergeShkurko** [comment]
@deakjahn ExtendedImage uses also for image switch

**Comment by deakjahn** [comment]
No, I didn't mean that. ExtendedImage can just replace it with a larger image but if you want to allow higher zoom levels without quality loss, you simply cannot generate ten times the size, the bitmap would be too large. Using tiled images would mean that only the part the user is actually looking at gets generated.

**Comment by SergeShkurko** [comment]
I understand your idea, it's just that this library is used not only for scaling, but also for turning pages. This is also quite an important factor.

**Comment by deakjahn** [comment]
Yes, sure. I would think about a PageView, just like now, where each page is a FlutterMap. I'll try to come up with something if I have the time. :-)

**Comment by SergeShkurko** [comment]
I will be glad to any help :)

**Comment by SergeShkurko** [comment]
## I start work on this issue

### Package `[native_pdf_renderer]` v6.0.0
- [x] iOS and macOS use a single codebase
- [x] Usage [plugin_platform_interface] for better work web
Usage pigeon on
- [x] iOS & macOS
- [x] Android
Texture rendering on
- [ ] iOS & macOS
- [ ] Android
- [ ] Web
- [ ] Provide docs for network pdf usage

### Package `[native_pdf_view]` v6.0.0
- [ ] Usage texture rendering
- [ ] Added vertical view
- [ ] Provide docs for #84
- [ ] Provide docs for network pdf usage

**Comment by SergeShkurko** [comment]
added in [pdfx](https://pub.dev/packages/pdfx)
